# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Update USFL Data

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install tqdm
        python -m pip install pandas
        python -m pip install requests
        python -m pip install pyarrow
        python -m pip install urllib3
        python -m pip install lxml
        python -m pip install bs4
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: runPythonScript
      env:
        USFL_KEY: ${{ secrets.USFL_KEY }}
      run: |
        python usfl.py
    - name: commit files
      run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "Update USFL Data" -a || echo "No changes to commit"
          git push origin main || echoh "No changes to commit"
          
